// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/class": {
    params: {};
  };
  "/class/one-day": {
    params: {};
  };
  "/class/regular": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/shop" | "/class" | "/class/one-day" | "/class/regular" | "/contact";
  };
  "common/pages/home-page.tsx": {
    id: "common/pages/home-page";
    page: "/";
  };
  "features/about/pages/about-page.tsx": {
    id: "features/about/pages/about-page";
    page: "/about";
  };
  "features/shop/pages/shop-page.tsx": {
    id: "features/shop/pages/shop-page";
    page: "/shop";
  };
  "features/class/pages/class-redirect-page.tsx": {
    id: "features/class/pages/class-redirect-page";
    page: "/class";
  };
  "features/class/pages/class-one-day-page.tsx": {
    id: "features/class/pages/class-one-day-page";
    page: "/class/one-day";
  };
  "features/class/pages/class-regular-page.tsx": {
    id: "features/class/pages/class-regular-page";
    page: "/class/regular";
  };
  "features/contact/pages/contact-page.tsx": {
    id: "features/contact/pages/contact-page";
    page: "/contact";
  };
};